services:
  peeker:
    container_name: peeker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:3000
    restart: always
    environment:
      - FLAG=FLAG{jago_bang_gg}
